[project]
name = "fileuploader-s3"
version = "0.1.0"
description = "Flask + MinIO File Uploader"
authors = [{ name = "Mark Wayne Menorca", email = "marcuwynu23@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "python-dotenv>=1.1.1",
    "boto3>=1.40.34",
    "botocore>=1.40.34",
    "markdown>=3.9",
    "waitress>=3.0.2",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
app = "fileuploader_s3.main:main"
